name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci
      
    - name: Build frontend
      working-directory: frontend
      run: npm run build
      
    - name: Create backend static directory
      run: |
        if (!(Test-Path "backend\static")) {
          New-Item -ItemType Directory -Path "backend\static" -Force
        }
      shell: powershell
      
    - name: Copy frontend to backend static
      run: |
        # Delete all files in backend/static except stub.html
        Get-ChildItem -Path "backend\static" -Recurse | Where-Object { $_.Name -ne "stub.html" } | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        
        # Copy frontend build files to backend/static
        Copy-Item -Recurse "frontend\build\*" "backend\static"
      shell: powershell
      
    - name: Build Go backend
      working-directory: backend
      run: |
        # Create build directory
        if (!(Test-Path "build")) {
          New-Item -ItemType Directory -Path "build" -Force
        }
        
        # Build for Windows
        $env:GOOS = "windows"
        $env:GOARCH = "amd64"
        go build -o "build\vebitor.exe" -ldflags="-s -w" .
      shell: powershell
      
    - name: Cleanup static files
      run: |
        # Delete all files in backend/static except stub.html
        Get-ChildItem -Path "backend\static" -Recurse | Where-Object { $_.Name -ne "stub.html" } | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
      shell: powershell
      
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: backend/build/vebitor.exe
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
